#!/bin/bash
function jsonval {
    temp=`cat $FILE | sed 's/\\\\\//\//g' | sed 's/[{}]//g' | awk -v k="text" '{n=split($0,a,","); for (i=1; i<=n; i++) print a[i]}' | sed 's/\"\:\"/\|/g' | sed 's/[\,]/ /g' | sed 's/\"//g' | grep -w $prop`
    echo ${temp##*|}
}

MARATHON_HOST="10.0.2.15:8080"
FILE=$1

if [[ $# -ne 1 ]]; then
    echo "Usage: $0 json-file"
    exit 0
fi

#curl -X POST -H "Content-Type: application/json" http://10.213.221.89:8080/v2/apps -d@$FILE
prop='id'
app_id=`jsonval | cut -d " " -f 2`


echo "Submitting application: $app_id"
curl -X PUT -H "Content-Type: application/json" http://master.mesos:8080/v2/apps/$app_id -d@$FILE
echo ""
